-- Hyprland main configuration (Lua format)
-- This file is templated - paths are resolved at provisioning time

-- Colors (generated by csg)
source = "{{ compositor_configs_xdg_config_home }}/hypr/colors.conf"

-- Modular configuration files
source = "{{ compositor_configs_xdg_config_home }}/hypr/keybindings.lua"
source = "{{ compositor_configs_xdg_config_home }}/hypr/monitors.lua"
source = "{{ compositor_configs_xdg_config_home }}/hypr/autostart.lua"
source = "{{ compositor_configs_xdg_config_home }}/hypr/window-rules.lua"
source = "{{ compositor_configs_xdg_config_home }}/hypr/animations.lua"
source = "{{ compositor_configs_xdg_config_home }}/hypr/input.lua"
source = "{{ compositor_configs_xdg_config_home }}/hypr/decoration.lua"
source = "{{ compositor_configs_xdg_config_home }}/hypr/cursor.lua"
source = "{{ compositor_configs_xdg_config_home }}/hypr/env-variables.lua"