-- Window rules configuration (Lua API)
-- Examples:
--   hl.window_rule({
--       name  = "float-pavucontrol",
--       match = { class = "^(pavucontrol)$" },
--       float = true,
--   })
--   hl.window_rule({
--       name  = "workspace-firefox",
--       match = { class = "^(firefox)$" },
--       workspace = 2,
--   })

-- Add your window rules here
