from __future__ import annotations

from typing import Protocol, runtime_checkable

from icon_templates_renderer.domain.exceptions import IconRendererError
from icon_templates_renderer.domain.models import (
    ListResult,
    MappingSetDefaultResult,
    MappingSetResult,
    MappingShowResult,
    RenderResult,
    ValidateResult,
)


@runtime_checkable
class OutputPort(Protocol):
    def render_result(self, result: RenderResult) -> None: ...
    def list_result(self, result: ListResult) -> None: ...
    def validate_result(self, result: ValidateResult) -> None: ...
    def mapping_show_result(self, result: MappingShowResult) -> None: ...
    def mapping_set_result(self, result: MappingSetResult) -> None: ...
    def mapping_set_default_result(self, result: MappingSetDefaultResult) -> None: ...
    def error(self, exc: IconRendererError) -> None: ...
    def message(self, msg: str) -> None: ...
