from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class ImageManagerPort(Protocol):
    def pull(self, image: str) -> None: ...

    def exists(self, image: str) -> bool: ...

    def remove(self, image: str) -> None: ...

    def list(self) -> list[str]: ...

    def get_default_registry(self) -> str: ...
