from __future__ import annotations

from contextlib import AbstractContextManager
from typing import Protocol, runtime_checkable

from cli_output.domain.views import (
    ConfigInfoView,
    CustomView,
    ErrorView,
    ListView,
    MessageView,
    RawView,
    ResultView,
)


@runtime_checkable
class Progress(Protocol):
    def advance(self, advance: int = 1) -> None: ...


@runtime_checkable
class Renderer(Protocol):
    def message(self, view: MessageView) -> None: ...
    def result(self, view: ResultView) -> None: ...
    def list(self, view: ListView) -> None: ...
    def error(self, view: ErrorView) -> None: ...
    def config(self, view: ConfigInfoView) -> None: ...
    def raw(self, view: RawView) -> None: ...
    def custom(self, view: CustomView) -> None: ...
    def status(self, message: str) -> AbstractContextManager[None]: ...
    def progress(self, total: int, message: str) -> AbstractContextManager[Progress]: ...
