email-client:
  color_scheme: ~
  template_dir: .
  output_dir: .
  color_mappings: {}
  variants:
    - name: email-client
      template: status-bar/email-client/default/icon.svg
      output: email-client.svg
