"""Terminal palette reload adapter — OSC 4/10/11/12 channel (AD-17, FR-6, R5).

Implements ``IDesktopReloader``: after the swap repoints
``current/colors.yaml`` (AD-17 consumer wiring, through the runtime
seeder), the adapter parses the pinned CSG colors.yaml schema and writes
the XTerm OSC terminal-palette byte sequence to the controlling terminal
``/dev/tty``, once per ``reload()`` invocation (shared-data-contract swap
step 5: "Terminal palette applied once from ``current/colors.yaml``").

Channel decision (the deliverable): OSC 4 sets ANSI palette slots 0-15
(``ESC]4;<slot>;<#rrggbb>ESC\\``), OSC 10/11/12 set default
foreground/background/cursor (``ESC]10;…ESC\\`` / ``ESC]11;…`` /
``ESC]12;``). The terminal consumers — starship prompt styles
(``starship.toml``: "bold red", "purple") and zsh's theme colors —
resolve against the terminal emulator's 256/16-color ANSI palette, so
recoloring the live terminal's palette recolors starship and zsh with
zero per-consumer work (no starship palette-import mechanism and no
terminal-emulator config exist in the spine). [consumer-wiring.md:34]
("Terminal colors: applied from ``current/colors.yaml`` by the terminal
adapter, not by a symlink"), [shared-data-contract.md swap step 5], FR-6.

Sequence byte shape: per-sequence byte-equivalent with the project's
pinned ``colors.sequences.j2`` template + its ``JinjaTemplateRenderer``
binary post-processing (``]`` → ``\\x1b]``, ``\\`` → ``\\x1b\\\\``):
16 × ``ESC]4;{i};{#rrggbb}ESC\\`` in ANSI-slot order (index = slot, from
the colors list enumerated), then ``ESC]10;{foreground}ESC\\``,
``ESC]11;{background}ESC\\``, ``ESC]12;{cursor}ESC\\`` — one ASCII
``bytes`` payload. Each sequence is self-terminating via ``ESC\\``, so
the payload concatenates them WITHOUT the template's per-line trailing
LF (the rendered artifact carries those newlines; omitting them is
functionally equivalent). The template is the spec of record — no
additional OSC codes are invented and no terminfo negotiation occurs.

AD-15 no-import note: ``color_scheme_generator`` is in the forbidden
import set (ARCHITECTURE-SPINE.md AD-15). This adapter MIRRORS the
``/dev/tty`` write mechanics of csg's ``adapters/terminal_applier.py``
(``open("/dev/tty", "wb")`` + flush) but NEVER imports it or its
templates; the sequence bytes are re-derived from ``current/colors.yaml``
because the runtime cache contains no ``colors.sequences`` artifact (the
shared-data-contract pins exactly ``colors.yaml``/``colors.conf``/
``colors.gtk.css`` — changing the artifact set is a spine change).

Strict parser coupling: ``colors.yaml`` is machine-generated by the
runtime's own pinned CSG template (``colors.yaml.j2``: three scalar keys
+ 16-item list, ``#rrggbb`` hex — CSG's ``Color.hex`` is validated
``^#[0-9a-fA-F]{6}$``, csg ``domain/models.py:15``). Parsing is
line-oriented and STRICT against that pinned shape: a missing OR
DUPLICATE scalar key, a non-``#rrggbb`` hex, a colors count other than
16, a second ``colors:`` header (split list), or ANY line outside the
pinned quoted-line shapes (unknown keys, junk, stray list items outside
the ``colors:`` block, blank lines) → warning + ``False`` (fail-loud;
the file is a cache artifact addressed by a hash of the templates that
produced it, so "unexpected shape" marks a broken cache entry, per R5 a
surfaced failure — never "best effort"). The template's trailing scalar
keys (``source_image``, ``backend``, ``generated_at``) are the only
additional lines accepted, each at most once. No PyYAML dependency: the
runtime ``pyproject.toml`` deps stay exactly ``typer`` + ``cli-output``,
and a hand-rolled parser is correct here only because the producer
template is pinned and hash-addressed.

AC-4-before-AC-3 precedence (family invariant, ``hyprpaper_reloader.py``
guard order): the vacuous check runs FIRST — ``current/`` absent →
``True``; ``current/colors.yaml`` entry absent (``not exists() and not
is_symlink()``) → ``True``, WITHOUT touching the TTY. Dangling/corrupt
entry and no-controlling-terminal-with-a-valid-entry are surfaced
``False`` failures that run only after a consumer entry exists (R5;
rt-2-5 review D2 resolution). A missing consumer entry wins over the
missing-TTY rule.

R5 headless decision: no ``sys.stdout.isatty()`` precondition — csg
guards on it because csg's stdout may be captured mid-pipeline; the
runtime adapter's contract is a SURFACED failure (spec-literal R5: the
terminal cannot be re-themed → ``False`` with ``TerminalColorApplier``
in ``ReconcileResult.reload_failures``). Attempting the write
unconditionally, wrapped in the mandated exception tuple
``(FileNotFoundError, PermissionError, OSError, ValueError)``, is what
makes a missing/headless TTY observable. The only vacuous success is "no
colors.yaml consumer entry at all".

Known Phase-2 limitations: this adapter recolors the LIVE terminal only.
A NEW shell still reads provisioning's rendered ``generated/palettes/
colors.sequences`` (``.zshrc.j2:30`` cat, provisioning-owned — the
runtime never edits provisioning-rendered configs, AD-5); closing that
gap is a future cross-domain provisioning delta. No daemon, no
per-terminal-emulator config writer (none exist in the spine).

References: [consumer-wiring.md:34], [shared-data-contract.md swap step
5], [ARCHITECTURE-SPINE.md AD-15], [R5], [FR-6].
"""

from __future__ import annotations

import logging
import os
import re
from pathlib import Path

from runtime.ports.desktop_reloader import IDesktopReloader

logger = logging.getLogger(__name__)

_HEX_PATTERN = re.compile(r"^#[0-9a-fA-F]{6}\Z")
_SCALAR_RE = re.compile(r'^(background|foreground|cursor):\s*"([^"]+)"\s*$')
_EXTRA_SCALAR_RE = re.compile(r'^(source_image|backend|generated_at):\s*"[^"]*"\s*$')
_COLORS_HEADER_RE = re.compile(r"^colors:\s*$")
_LIST_ITEM_RE = re.compile(r'^  - "([^"]+)"\s*$')
_EXPECTED_COLOR_COUNT = 16


def _resolve_state_root(state_root: Path | None) -> Path:
    """Resolve the runtime state root (absolute).

    Mirrors ``cli/main.py`` ``_resolve_state_root`` semantics:
    ``$XDG_STATE_HOME/dotfiles`` (default ``~/.local/state/dotfiles``),
    expanded and resolved to an absolute path. An explicit ``state_root``
    (tests, composition root) is used as-is after the same expansion.
    """
    if state_root is not None:
        return state_root.expanduser().resolve()
    xdg_state = Path(os.environ.get("XDG_STATE_HOME") or Path.home() / ".local" / "state")
    return (xdg_state / "dotfiles").expanduser().resolve()


def _parse_colors_yaml(text: str) -> tuple[str, str, str, tuple[str, ...]] | None:
    """Parse the pinned ``colors.yaml.j2`` schema (strict).

    Returns ``(background, foreground, cursor, colors16)`` or ``None`` on
    ANY deviation from the pinned shape: a missing or duplicate scalar
    key, a non-``#rrggbb`` hex, a colors list whose count != 16 (index =
    ANSI slot), a second ``colors:`` header (split list), or any line
    that matches none of the pinned quoted-line shapes (unknown keys,
    junk, stray list items outside the ``colors:`` block, blank lines).
    The template's trailing scalar keys (``source_image``, ``backend``,
    ``generated_at``) are the only additional lines accepted, each at
    most once.
    """
    scalars: dict[str, str] = {}
    extras: set[str] = set()
    colors: list[str] = []
    in_colors = False
    colors_header_seen = False
    for raw in text.splitlines():
        line = raw.rstrip("\r")
        if in_colors:
            item = _LIST_ITEM_RE.match(line)
            if item is not None:
                colors.append(item.group(1))
                continue
            in_colors = False
        scalar = _SCALAR_RE.match(line)
        if scalar is not None:
            key = scalar.group(1)
            if key in scalars:
                return None
            scalars[key] = scalar.group(2)
            continue
        if _COLORS_HEADER_RE.match(line) is not None:
            if colors_header_seen:
                return None
            colors_header_seen = True
            in_colors = True
            continue
        extra = _EXTRA_SCALAR_RE.match(line)
        if extra is not None:
            if extra.group(1) in extras:
                return None
            extras.add(extra.group(1))
            continue
        return None
    if set(scalars) != {"background", "foreground", "cursor"}:
        return None
    values = [*scalars.values(), *colors]
    if len(colors) != _EXPECTED_COLOR_COUNT:
        return None
    if any(_HEX_PATTERN.match(value) is None for value in values):
        return None
    return scalars["background"], scalars["foreground"], scalars["cursor"], tuple(colors)


def _build_payload(colors: tuple[str, ...], foreground: str, background: str, cursor: str) -> bytes:
    """Build the OSC payload — per-sequence byte-equivalent with the pinned
    ``colors.sequences.j2`` shape, concatenated without the template's
    per-line trailing LF."""
    parts = [f"\x1b]4;{index};{hex_value}\x1b\\" for index, hex_value in enumerate(colors)]
    parts.append(f"\x1b]10;{foreground}\x1b\\")
    parts.append(f"\x1b]11;{background}\x1b\\")
    parts.append(f"\x1b]12;{cursor}\x1b\\")
    return "".join(parts).encode("ascii")


class TerminalColorApplier(IDesktopReloader):
    """Adapter that applies the terminal palette to the live terminal.

    Reads ``state_root/current/colors.yaml`` (FS authority, NFR-3 —
    the reload loop passes no state), parses it strictly against the
    pinned CSG schema, and writes the derived OSC 4/10/11/12 payload to
    ``/dev/tty`` (or the injected ``tty_path`` seam in tests) exactly
    once per ``reload()``.

    Args:
        state_root: explicit runtime state root. When ``None``, resolved
            to ``$XDG_STATE_HOME/dotfiles`` (default ``~/.local/state/
            dotfiles``). The CLI composition root passes the SAME
            state_root the reconcile use case writes.
        tty_path: the apply TARGET. When ``None``, defaults to
            ``/dev/tty``. The injected value is the sanctioned test seam
            for both unit and integration layers — the real ``/dev/tty``
            is never opened in tests.
    """

    def __init__(self, state_root: Path | None = None, tty_path: Path | None = None) -> None:
        self._state_root: Path = _resolve_state_root(state_root)
        self._tty_path: Path = tty_path if tty_path is not None else Path("/dev/tty")

    def reload(self) -> bool:
        """Parse ``current/colors.yaml`` and apply the palette to the terminal.

        Returns:
            True when the palette was applied successfully, or vacuously
            when ``current/colors.yaml`` does not exist (nothing to
            apply). False on a dangling symlink, an unparseable/malformed
            colors.yaml, an unreadable file, or a ``/dev/tty`` open/write
            failure — each logged with the cause (surfaced failure, per
            R5; the reconcile use case collects the class name into
            ``ReconcileResult.reload_failures``).

            Precedence (family invariant): the AC-4 vacuous state wins
            over the missing-TTY rule — a missing consumer entry returns
            ``True`` without touching the TTY; the TTY checks run only
            AFTER a consumer entry exists.
        """
        current_dir = self._state_root / "current"
        if not current_dir.is_dir():
            logger.debug("no current/ dir under %s; no terminal palette to apply", self._state_root)
            return True
        link = current_dir / "colors.yaml"
        if not link.exists() and not link.is_symlink():
            logger.debug("no colors.yaml entry in %s; nothing to apply", current_dir)
            return True
        if link.is_symlink() and not link.exists():
            logger.warning("TerminalColorApplier reload failed: dangling symlink %s", link)
            return False
        try:
            text = link.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError) as exc:
            logger.warning("TerminalColorApplier reload failed: cannot read %s: %s", link, exc)
            return False
        parsed = _parse_colors_yaml(text)
        if parsed is None:
            logger.warning(
                "TerminalColorApplier reload failed: colors.yaml is not the pinned schema: %s",
                link,
            )
            return False
        background, foreground, cursor, colors = parsed
        payload = _build_payload(colors, foreground, background, cursor)
        try:
            with open(self._tty_path, "wb") as tty:
                tty.write(payload)
                tty.flush()
        except (FileNotFoundError, PermissionError, OSError, ValueError) as exc:
            logger.warning(
                "TerminalColorApplier reload failed: cannot write palette to %s: %s",
                self._tty_path,
                exc,
            )
            return False
        logger.debug(
            "TerminalColorApplier: applied %d-byte palette to %s", len(payload), self._tty_path
        )
        return True
